### ISSUE TITLE
Modify analysis to use standardized variables

### ISSUE THREAD

**Issue by eogmartins** [BIOL325-Ecological-Analyses-2021/githublab-instructors#1]
@oconnorbryce Can you please change the code in ant_report.Rmd to run the analysis with standardized predictor variables?

**Comment by oconnorbryce** [comment]
I completed creating the standardized variables for the analysis

**Comment by eogmartins** [comment]
Hey @oconnorbryce , you just transformed the variable. I would like you to actually also include the transformed variables in the analysis and prediction plots.

**Comment by oconnorbryce** [comment]
I have edited the analysis and prediction plots as well in a recent pull request on new branch called standardized
